---
- name: Create Dockerfile, images and build containers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Dockerfile
      template:
        src: Dockerfile.j2
        dest: Dockerfile

    # As seen this is the only way to make arm images, otherwise dpkg gives error code 100.
    # Problem: https://github.com/docker/buildx/issues/495
    # Solution: https://github.com/docker/buildx/issues/495#issuecomment-761562905
    - name: Setup builder
      command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Create builder
      command: docker buildx create --name multiarch --driver docker-container --use
      ignore_errors: true

    - name: Use builder
      command: docker buildx inspect --bootstrap

    - name: Build containers
      include_tasks: build_containers.yml
      with_items: "{{ dockerhub_image_architectures }}"


- name: Execute Java role in Docker containers
  hosts: jdk_containers
  connection: localhost
  gather_facts: true
  vars:
    - java_jdk_vendor: "{{ jdk_vendor if jdk_vendor is defined and jdk_vendor is not sameas None and jdk_vendor != '' else 'openjdk' }}"
    - java_open_jdk_version: "{{ jdk_version if jdk_version is defined and jdk_version is not sameas None and jdk_version != '' }}"
    - java_open_jdk_version_major: "{{ jdk_major if jdk_major is defined and jdk_major is not sameas None and jdk_major != ''}}"
  tasks:
    - name: Execute role
      include_tasks: execute_role.yml

- name: Deploy images to DockerHub
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:

    - name: Check failed containers
      set_fact:
        failed_architectures: "{{ failed_architectures + [ item ] }}"
      with_items: "{{ groups['jdk_containers'] }}"
      when: "{{ hostvars[item]['failed_execution'] is defined and hostvars[item]['failed_execution'] == True }}"

    - name: Deploy images
      include_tasks: deploy_images.yml
      with_items: "{{ dockerhub_image_architectures }}"


- name: Deploy multiarch manifest to DockerHub and cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create manifest
      command: docker manifest create idealista/jdk:{{ docker_tag }}
                {% for architecture in dockerhub_image_architectures %}
                  {% if failed_architectures is not defined or not failed_architectures | join('|') | regex_search(architecture) %}
                    --amend idealista/jdk:{{ docker_tag + '-' + architecture }}
                  {% endif %}
                {% endfor %}

    - name: Push manifest
      command: docker manifest push idealista/jdk:{{ docker_tag }}

    - name: Delete builder
      command: docker buildx rm multiarch

    - name: Example using fail and when together
      fail:
        msg: Atleast one of the architectures could not be uploaded see logs for more information.
      when: failed_architectures is defined and failed_architectures | length != 0
